In [6]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_csv("en_climate_daily_BC_1108395_2019_P1D.csv")
data

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Data Quality,Max Temp (Â°C),...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,-123.18,49.19,VANCOUVER INTL A,1108395,2019-01-01,2019,1,1,NaN,5.3,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
1,-123.18,49.19,VANCOUVER INTL A,1108395,2019-01-02,2019,1,2,NaN,5.5,...,0.0,T,3.4,NaN,NaN,NaN,6.0,NaN,41.0,NaN
2,-123.18,49.19,VANCOUVER INTL A,1108395,2019-01-03,2019,1,3,NaN,9.5,...,0.0,NaN,54.8,NaN,NaN,NaN,14.0,NaN,54.0,NaN
3,-123.18,49.19,VANCOUVER INTL A,1108395,2019-01-04,2019,1,4,NaN,10.4,...,0.0,NaN,9.6,NaN,NaN,NaN,15.0,NaN,45.0,NaN
4,-123.18,49.19,VANCOUVER INTL A,1108395,2019-01-05,2019,1,5,NaN,8.7,...,0.0,NaN,3.2,NaN,NaN,NaN,10.0,NaN,33.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,-123.18,49.19,VANCOUVER INTL A,1108395,2019-12-27,2019,12,27,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,-123.18,49.19,VANCOUVER INTL A,1108395,2019-12-28,2019,12,28,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
362,-123.18,49.19,VANCOUVER INTL A,1108395,2019-12-29,2019,12,29,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
363,-123.18,49.19,VANCOUVER INTL A,1108395,2019-12-30,2019,12,30,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,-123.18,49.19,VANCOUVER INTL A,1108395,2019-12-31,2019,12,31,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
wget --content-disposition "https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=51442&Year=2013&Month=12&Day=14&timeframe=2&submit= Download+Data"

In [14]:
data2 = pd.read_excel("clean-bike-theft.xlsx")
data2

,Occurred_Date_From,ReformattedTime,DateTime,Occurred_Time_From,Description,district,Weekday,Month,Year,100 Block,100 Block CLEANED,AddressConsolidated,Lat,Long
0,2008-01-01,00:00:00,2008-01-01 00:00:00,0,THEFT BICYCLE UNDER $5000,4.0,3,January,2008,600 W 7TH AVE,600 W 7TH AVE,600 W 7TH AVE,49.265008,-123.118
1,2008-01-01,00:00:00,2008-01-01 00:00:00,0,THEFT BICYCLE UNDER $5000,4.0,3,January,2008,700 W 7TH AVE,700 W 7TH AVE,700 W 7TH AVE,49.265040,-123.12
2,2008-01-01,12:00:00,2008-01-01 12:00:00,1200,THEFT BICYCLE UNDER $5000,4.0,3,January,2008,3500 MAIN ST,3500 MAIN ST,3500 MAIN ST,49.253888,-123.101
3,2008-01-04,18:00:00,2008-01-04 18:00:00,1800,THEFT BICYCLE UNDER $5000,4.0,6,January,2008,3200 W 3RD AVE,3200 W 3RD AVE,3200 W 3RD AVE,49.269359,-123.176
4,2008-01-06,08:00:00,2008-01-06 08:00:00,800,THEFT BICYCLE UNDER $5000,1.0,1,January,2008,1000 W GEORGIA ST,1000 W GEORGIA ST,1000 W GEORGIA ST,49.284481,-123.121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7838,2012-12-28,02:00:00,2012-12-28 02:00:00,200,THEFT BICYCLE UNDER $5000,1.0,6,December,2012,800 BROUGHTON ST,800 BROUGHTON ST,800 BROUGHTON ST,49.287907,-123.13
7839,2012-12-29,21:00:00,2012-12-29 21:00:00,2100,THEFT BICYCLE UNDER $5000,3.0,7,December,2012,4700 MANOR ST,4700 MANOR ST,4700 MANOR ST,49.242700,-123.039
7840,2012-12-30,10:32:00,2012-12-30 10:32:00,1032,THEFT BICYCLE UNDER $5000,3.0,1,December,2012,300 E 6TH AVE,300 E 6TH AVE,300 E 6TH AVE,49.265460,-123.099
7841,2012-12-30,22:30:00,2012-12-30 22:30:00,2230,THEFT BICYCLE UNDER $5000,4.0,1,December,2012,300 E 20TH AVE,300 E 20TH AVE,300 E 20TH AVE,49.252937,-123.099
7842,2012-12-31,18:45:00,2012-12-31 18:45:00,1845,THEFT BICYCLE OVER $5000,3.0,2,December,2012,3600 COMMERCIAL ST,3600 COMMERCIAL ST,3600 COMMERCIAL ST,49.252555,-123.068