In [1]:
import numpy as np
import pandas as pd
import glob

https://climate.weather.gc.ca/glossary_e.html#weather
<br>
Good weather means:
<br>
- Clear 
- Mainly clear 
- Mostly cloudy
- Cloudy data

In [2]:
filename = "hourly_2014_2019/2019/en_climate_hourly_BC_1108395_01-2019_P1H.csv"
df = pd.read_csv(filename, index_col=None, header=0, parse_dates = ["Date/Time"])

#Get date time and weather status
filterDf = df[["Date/Time","Year", "Month", "Day", "Time", "Weather"]]
filterDf

FileNotFoundError: [Errno 2] File b'hourly_2014_2019/2019/en_climate_hourly_BC_1108395_01-2019_P1H.csv' does not exist: b'hourly_2014_2019/2019/en_climate_hourly_BC_1108395_01-2019_P1H.csv'

In [3]:
filterDf["Weather"].unique()

NameError: name 'filterDf' is not defined

In [4]:
#Add a column for Date only
filterDf["Date"] = filterDf['Date/Time'].apply(lambda x:x.date().strftime('%Y-%m-%d'))
filterDf

NameError: name 'filterDf' is not defined

In [4]:
#Ensures there exist at least 1 weather record for each day in the current month
dfDropna = filterDf
assert(len(dfDropna.Date.unique()) == 31)

In [42]:
dates = dfDropna.Date.unique()
for day in dates:
    dateDf = filterDf[filterDf["Date"] == day]
    dayWeather = test["Weather"].value_counts().idxmax()
    fillMissing = dateDf
    fillMissing["Weather"] = fillMissing["Weather"].replace(to_replace = np.nan, value = dayWeather)

array(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
       '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
       '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
       '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
       '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
       '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
       '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
       '2019-01-29', '2019-01-30', '2019-01-31'], dtype=object)

In [31]:
test = dfDropna[dfDropna["Date"] == "2019-01-01"]
test

             Date/Time  Year  Month  Day   Time        Weather        Date
0  2019-01-01 00:00:00  2019      1    1  00:00            NaN  2019-01-01
1  2019-01-01 01:00:00  2019      1    1  01:00  Mostly Cloudy  2019-01-01
2  2019-01-01 02:00:00  2019      1    1  02:00            NaN  2019-01-01
3  2019-01-01 03:00:00  2019      1    1  03:00            NaN  2019-01-01
4  2019-01-01 04:00:00  2019      1    1  04:00         Cloudy  2019-01-01
5  2019-01-01 05:00:00  2019      1    1  05:00            NaN  2019-01-01
6  2019-01-01 06:00:00  2019      1    1  06:00            NaN  2019-01-01
7  2019-01-01 07:00:00  2019      1    1  07:00         Cloudy  2019-01-01
8  2019-01-01 08:00:00  2019      1    1  08:00            NaN  2019-01-01
9  2019-01-01 09:00:00  2019      1    1  09:00            NaN  2019-01-01
10 2019-01-01 10:00:00  2019      1    1  10:00         Cloudy  2019-01-01
11 2019-01-01 11:00:00  2019      1    1  11:00            NaN  2019-01-01
12 2019-01-01 12:00:00  2019      1    1  12:00            NaN  2019-01-01
13 2019-01-01 13:00:00  2019      1    1  13:00         Cloudy  2019-01-01
14 2019-01-01 14:00:00  2019      1    1  14:00            NaN  2019-01-01
15 2019-01-01 15:00:00  2019      1    1  15:00            NaN  2019-01-01
16 2019-01-01 16:00:00  2019      1    1  16:00         Cloudy  2019-01-01
17 2019-01-01 17:00:00  2019      1    1  17:00            NaN  2019-01-01
18 2019-01-01 18:00:00  2019      1    1  18:00            NaN  2019-01-01
19 2019-01-01 19:00:00  2019      1    1  19:00         Cloudy  2019-01-01
20 2019-01-01 20:00:00  2019      1    1  20:00            NaN  2019-01-01
21 2019-01-01 21:00:00  2019      1    1  21:00            NaN  2019-01-01
22 2019-01-01 22:00:00  2019      1    1  22:00         Cloudy  2019-01-01
23 2019-01-01 23:00:00  2019      1    1  23:00            NaN  2019-01-01

In [33]:
#determine the weather of the day by finding the most weather occurence
#https://stackoverflow.com/questions/48590268/pandas-get-the-most-frequent-values-of-a-column
dayWeather = test["Weather"].value_counts().idxmax()
dayWeather

'Cloudy'

In [37]:
fillMissing = test

fillMissing["Weather"] = fillMissing["Weather"].replace(to_replace = np.nan, value = dayWeather)
fillMissing

/home/leo/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

             Date/Time  Year  Month  Day   Time        Weather        Date
0  2019-01-01 00:00:00  2019      1    1  00:00         Cloudy  2019-01-01
1  2019-01-01 01:00:00  2019      1    1  01:00  Mostly Cloudy  2019-01-01
2  2019-01-01 02:00:00  2019      1    1  02:00         Cloudy  2019-01-01
3  2019-01-01 03:00:00  2019      1    1  03:00         Cloudy  2019-01-01
4  2019-01-01 04:00:00  2019      1    1  04:00         Cloudy  2019-01-01
5  2019-01-01 05:00:00  2019      1    1  05:00         Cloudy  2019-01-01
6  2019-01-01 06:00:00  2019      1    1  06:00         Cloudy  2019-01-01
7  2019-01-01 07:00:00  2019      1    1  07:00         Cloudy  2019-01-01
8  2019-01-01 08:00:00  2019      1    1  08:00         Cloudy  2019-01-01
9  2019-01-01 09:00:00  2019      1    1  09:00         Cloudy  2019-01-01
10 2019-01-01 10:00:00  2019      1    1  10:00         Cloudy  2019-01-01
11 2019-01-01 11:00:00  2019      1    1  11:00         Cloudy  2019-01-01
12 2019-01-01 12:00:00  2019      1    1  12:00         Cloudy  2019-01-01
13 2019-01-01 13:00:00  2019      1    1  13:00         Cloudy  2019-01-01
14 2019-01-01 14:00:00  2019      1    1  14:00         Cloudy  2019-01-01
15 2019-01-01 15:00:00  2019      1    1  15:00         Cloudy  2019-01-01
16 2019-01-01 16:00:00  2019      1    1  16:00         Cloudy  2019-01-01
17 2019-01-01 17:00:00  2019      1    1  17:00         Cloudy  2019-01-01
18 2019-01-01 18:00:00  2019      1    1  18:00         Cloudy  2019-01-01
19 2019-01-01 19:00:00  2019      1    1  19:00         Cloudy  2019-01-01
20 2019-01-01 20:00:00  2019      1    1  20:00         Cloudy  2019-01-01
21 2019-01-01 21:00:00  2019      1    1  21:00         Cloudy  2019-01-01
22 2019-01-01 22:00:00  2019      1    1  22:00         Cloudy  2019-01-01
23 2019-01-01 23:00:00  2019      1    1  23:00         Cloudy  2019-01-01