In [1]:
import numpy as np
import pandas as pd

# Read in the original dataset
data = pd.read_csv("crimedata_csv_all_years.csv")
data = data[data['TYPE'] == "Theft of Bicycle"]
data = data.sort_values(by="YEAR", axis=0)
data.reset_index(inplace=True, drop=True)

# Retrun filtered thefts by bicycle, sorted by year
data.to_csv("raw_bike_data.csv", index=False)
data

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft of Bicycle,2003,8,28,22,0,29XX ASH ST,Fairview,491442.679015,5.456291e+06
1,Theft of Bicycle,2003,10,3,16,28,20XX WALL ST,Grandview-Woodland,495505.932258,5.459267e+06
2,Theft of Bicycle,2003,8,20,20,30,20XX YORK AVE,Kitsilano,488974.181520,5.457668e+06
3,Theft of Bicycle,2003,6,17,8,0,7XX TEMPLETON DR,Grandview-Woodland,495645.272537,5.458368e+06
4,Theft of Bicycle,2003,8,7,8,0,7XX TEMPLETON DR,Grandview-Woodland,495645.272537,5.458368e+06
...,...,...,...,...,...,...,...,...,...,...
30974,Theft of Bicycle,2019,8,8,12,0,7XX W GEORGIA ST,Central Business District,491407.744286,5.458872e+06
30975,Theft of Bicycle,2019,3,25,17,0,34XX TERRA VITA PL,Hastings-Sunrise,497820.174655,5.458189e+06
30976,Theft of Bicycle,2019,7,30,16,26,57XX FRASER ST,Sunset,493412.152473,5.453336e+06
30977,Theft of Bicycle,2019,10,10,0,0,11XX ODLUM DR,Grandview-Woodland,494483.821861,5.458006e+06
30978,Theft of Bicycle,2019,8,22,14,30,62XX KILLARNEY ST,Killarney,496685.317174,5.452640e+06